#!/usr/bin/env python
import serial
import rospy
import socket
import std_msgs.msg

rospy.init_node("send_pwm")
rate = rospy.Rate(20)

port_name = rospy.get_param("~port", "/dev/ACM0")

port = serial.Serial(port_name, baudrate=57600)

pwml = 1500
pwmr = 1500
pwmf = 1500

def listener():
	rospy.Subscriber("/left_pwm", std_msgs.msg.Float64, callback, callback_args=0)
	rospy.Subscriber("/right_pwm", std_msgs.msg.Float64, callback, callback_args=1)
	rospy.Subscriber("/front_pwm", std_msgs.msg.Float64, front_callback, callback_args=2)
	rospy.spin()

def callback(data, left):
	global pwml, pwmr
	if(arg==0):
		pwml = int(data.data)
	elif(arg==1):
		pwmr = int(data.data)
	elif(arg==2):
		pwmf = int(data.data)

def talker():
	global pwml, pwmr, pwmf, rate, port
	if(pwml>1900):
		pwml = 1900
	if(pwml<1100):
		pwml = 1100
	if(pwmr>1900):
		pwmr = 1900
	if(pwmr<1100):
		pwmr = 1100
	if(pwmf>1900):
		pwmf = 1900
	if(pwmf<1100):
		pwmf = 1100
	port.write("%d:%d:%d:|"%(pwml,pwmr,pwmf))
	rospy.loginfo("%d:%d:%d:|"%(pwml,pwmr,pwmf))
	rate.sleep()

listener()